import turtle
t = turtle

screen = turtle.Screen()
screen.screensize(800,800)
screen.bgcolor('lightsteelblue')

t.penup()
t.speed(2000)
t.penup()
t.goto(0, 50)
t.pendown()
t.penup()
t.goto(0, 200)
t.pendown()
t.write("Merry Christmas!!", font=("arial", 30, "bold"), align="center")


t_ground=turtle.Turtle()
t_ground.speed(0)
t_ground.pencolor('white')
t_ground.fillcolor('white')
t_ground.penup()
t_ground.goto(-1000,-100)
t_ground.pendown()
t_ground.begin_fill()
t_ground.goto(1000,-100)
t_ground.goto(1000,-1000)
t_ground.goto(1000,-1000)
t_ground.goto(-1000,-1000)
t_ground.end_fill()
t.penup()
t.goto(0,0)


#snowman
t_ground.fillcolor('white')
t_ground.penup()
t_ground.begin_fill()
t_ground.goto(-100,-100)
t_ground.pendown()
t_ground.circle(50)
t_ground.end_fill()
t_ground.penup()
t_ground.begin_fill()
t_ground.goto(-100,0)
t_ground.pendown()
t_ground.circle(35)
t_ground.end_fill()
t_ground.penup()
t_ground.begin_fill()
t_ground.goto(-100,70)
t_ground.pendown()
t_ground.circle(25)
t_ground.end_fill()

#snowman eyes
t_ground.penup()
t_ground.pencolor('black')
t_ground.fillcolor('black')
t_ground.begin_fill()
t_ground.goto(-90,90)
t_ground.circle(5)
t_ground.end_fill()
t_ground.penup()
t_ground.begin_fill()
t_ground.goto(-110,90)
t_ground.circle(5)
t_ground.end_fill()
t_ground.penup()

#snowman nose
t_ground.goto(-100,85)
t_ground.pencolor('orange')
t_ground.fillcolor('orange')
t_ground.pendown()
t_ground.begin_fill()
t_ground.goto(-85,82)
t_ground.goto(-100,75)
t_ground.goto(-100,85)
t_ground.end_fill()
t_ground.hideturtle()


#snowman mouth
t_ground.penup()
t_ground.goto(-100,66)
t_ground.pencolor("black")
t_ground.fillcolor("black")
t_ground.begin_fill()
t_ground.pendown()
t_ground.circle(2)
t_ground.end_fill()
t_ground.penup()
t_ground.begin_fill()
t_ground.goto(-105,67)
t_ground.pendown()
t_ground.circle(2)
t_ground.end_fill()
t_ground.penup()
t_ground.begin_fill()
t_ground.goto(-110,69)
t_ground.pendown()
t_ground.circle(2)
t_ground.end_fill()
t_ground.penup()
t_ground.begin_fill()
t_ground.goto(-95,67)
t_ground.pendown()
t_ground.circle(2)
t_ground.end_fill()
t_ground.penup()
t_ground.begin_fill()
t_ground.goto(-90,69)
t_ground.pendown()
t_ground.circle(2)
t_ground.end_fill()


#stump
t.pencolor('brown')
t.pensize(15)
t.penup()
t.goto(50,-50)
t.pendown()
t.goto(50,-125)
t.penup()
t.pensize(1)

#top of the tree
t.pencolor("green")
t.fillcolor("green")
t.goto(50,50)
t.pendown()
t.begin_fill()
t.goto(10,10)
t.goto(90,10)
t.goto(50,50)
t.penup()
t.end_fill()

#second layer
t.goto(50,25)
t.pendown()
t.begin_fill()
t.goto(-10,-25)
t.goto(110,-25)
t.goto(50,25)
t.penup()
t.end_fill()

#third layer
t.goto(50,0)
t.pendown()
t.begin_fill()
t.goto(-30,-75)
t.goto(130,-75)
t.goto(50,0)
t.penup()
t.end_fill()


#part of gift
t.penup()
t.goto(-230,-100)
t.pendown()
t.fillcolor("grey")
t.begin_fill()
t.setheading(90)
t.circle(15,180)
t.goto(-245,-100)
t.goto(-215,-100)
t.end_fill()

#gift box
t.penup()
t.fillcolor("chocolate")
t.begin_fill()
t.goto(150,0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.end_fill()

#vertical part of ribbon
t.penup()
t.goto(190,0)
t.pendown()
t.fillcolor("silver")
t.begin_fill()
t.forward(100)
t.left(90)
t.forward(20)
t.left(90)
t.forward(100)
t.left(90)
t.forward(20)
t.end_fill()

#horozontial part of ribbon
t.penup()
t.goto(150,-40)
t.setheading(0)
t.pendown()
t.begin_fill()
t.forward(100)
t.left(90)
t.forward(20)
t.left(90)
t.forward(100)
t.left(90)
t.forward(20)
t.end_fill()

#bow on present
t.penup()
t.goto(200,0)
t.pendown()
t.dot(20, "light pink")


#left loop of bow
t.penup()
t.goto(190,10)
t.setheading(135)
t.pendown()
t.pencolor("light pink")
t.fillcolor("light pink")
t.begin_fill()
t.circle(15,180)
t.goto(200,0)
t.end_fill()


#right loop
t.penup()
t.goto(210,10)
t.setheading(45)
t.pendown()
t.begin_fill()
t.circle(-15,180)
t.goto(200,0)
t.end_fill()




#LAST LINE OF CODE
turtle.done()